# Generated by Django 5.0 on 2023-12-30 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0007_location_meetup_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
